import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen gradient-bg relative overflow-x-hidden">
      <header className="fixed top-0 left-0 right-0 z-50 glass-strong py-4">
        <div className="max-w-7xl mx-auto px-6 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center">
              <span className="text-xl">🎯</span>
            </div>
            <span className="text-xl font-bold text-white">InterviewAI</span>
          </Link>
          <Link href="/" className="text-white/70 hover:text-white transition-colors">← Back to Home</Link>
        </div>
      </header>

      <div className="pt-32 pb-20 px-6 max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">Terms of Service</h1>
          <p className="text-white/50">Last updated: February 1, 2026</p>
        </div>

        <div className="glass-strong rounded-3xl p-8 md:p-12 space-y-8">
          {[
            {
              title: "1. Acceptance of Terms",
              content: "By accessing and using InterviewAI, you agree to be bound by these Terms of Service. If you do not agree, please do not use our platform.",
            },
            {
              title: "2. Description of Service",
              content: "InterviewAI provides AI-powered technical interview preparation services, including practice questions, code execution environments, and AI-generated feedback. Our services are provided 'as is' and we continuously improve them.",
            },
            {
              title: "3. User Accounts",
              content: "You are responsible for maintaining the security of your account. You must provide accurate information when creating an account and keep your credentials confidential. You are responsible for all activity under your account.",
            },
            {
              title: "4. Acceptable Use",
              content: "You agree not to misuse our services. This includes attempting to reverse-engineer our AI models, sharing account credentials, using automated scripts to access the service, or using the platform for any illegal purposes.",
            },
            {
              title: "5. Intellectual Property",
              content: "All content generated by InterviewAI, including questions, feedback, and analysis, is owned by InterviewAI. Your code submissions remain your intellectual property. You grant us a limited license to process your submissions for service improvement.",
            },
            {
              title: "6. Payment & Refunds",
              content: "Paid plans are billed in advance on a monthly or annual basis. You may cancel at any time, and your access will continue until the end of your billing period. Refunds may be issued at our discretion within 14 days of purchase.",
            },
            {
              title: "7. Privacy",
              content: "Your privacy is important to us. Please review our Privacy Policy, which explains how we collect, use, and protect your personal information.",
            },
            {
              title: "8. Limitation of Liability",
              content: "InterviewAI is a practice tool and does not guarantee employment outcomes. We are not liable for any interview results, hiring decisions, or career outcomes. Our maximum liability is limited to the amount you paid for the service.",
            },
            {
              title: "9. Changes to Terms",
              content: "We may update these terms from time to time. We will notify you of material changes via email or a prominent notice on our platform. Continued use constitutes acceptance of updated terms.",
            },
            {
              title: "10. Contact",
              content: "If you have questions about these Terms, please contact us at legal@interviewai.com.",
            },
          ].map((section, idx) => (
            <div key={idx}>
              <h2 className="text-lg font-semibold text-white mb-2">{section.title}</h2>
              <p className="text-white/60 leading-relaxed">{section.content}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
